//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthorizationEntities : DbContext
    {
        public AuthorizationEntities()
            : base("name=AuthorizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_Action> sys_Action { get; set; }
        public virtual DbSet<sys_App> sys_App { get; set; }
        public virtual DbSet<sys_Dictionary> sys_Dictionary { get; set; }
        public virtual DbSet<sys_DictionaryType> sys_DictionaryType { get; set; }
        public virtual DbSet<sys_ErrorLog> sys_ErrorLog { get; set; }
        public virtual DbSet<sys_ForbidIp> sys_ForbidIp { get; set; }
        public virtual DbSet<sys_LoginLog> sys_LoginLog { get; set; }
        public virtual DbSet<sys_Member> sys_Member { get; set; }
        public virtual DbSet<sys_MemberExtend> sys_MemberExtend { get; set; }
        public virtual DbSet<sys_Menu> sys_Menu { get; set; }
        public virtual DbSet<sys_OperLog> sys_OperLog { get; set; }
        public virtual DbSet<sys_Orgnization> sys_Orgnization { get; set; }
        public virtual DbSet<sys_Role> sys_Role { get; set; }
        public virtual DbSet<vw_MemberRole> vw_MemberRole { get; set; }
        public virtual DbSet<vw_AppMenu> vw_AppMenu { get; set; }
    }
}
