//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_ErrorLog
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public string RealName { get; set; }
        public string LogContent { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string Ip { get; set; }
    }
}
